language: php
sudo: false
services: redis-server
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
env:
  global:
    - CC_TEST_REPORTER_ID=f3943a2b33c2e2ab9c402c09daa14afeaa426b8e9a60dba7bbc36ce2a37c17b1
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - composer self-update
  - composer install --no-interaction
script:
  - vendor/bin/phpunit --coverage-clover clover.xml
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
